### PR TITLE
Use regex for search and inform the user if no results are found

### PR DESCRIPTION
**Pull request by AIWintermuteAI**
Hi, @simbake !
Thanks for the useful extension. I want to feature it in my YT video about local LLMs - and I made two small tweaks:
- You can now elaborate on what you want to do with the result. For example entering search "weather in Amsterdam" and tell me what should I wear. would search online for phrase in double quotation marks only. Then LLM would use this information to answer the question.
- If nothing was returned as search result, currently the model does not inform the user about that. I modified the context to inform the user that no search results were found and use information from the training data. 
Screenshot 2023-11-17 at 17 51 03

Let me know if there are some changes that need to be made.

### CODE REVIEW

**Comment by simbake** [comment]
Does the it work without the quotes? I would prefer it didn't need those.

**Comment by AIWintermuteAI** [comment]
Yes!
I just modified readme to point that both with and without quotes works.

**Comment by AIWintermuteAI** [comment]
Okay, I tested it some more and fixed the case where no search word is found. 
Do you have any opportunity to test it as well, using CPU inference?

**Comment by simbake** [comment]
I will do that tomorrow. Sorry for not replying in time, I was a bit busy today.

**Review by simbake — APPROVED** [review]

**Pull request merged**
